In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files

uploaded = files.upload()

filename = next(iter(uploaded))

df = pd.read_csv("Online_Retail.csv")

print("Dataset loaded successfully!")

Saving Online_Retail.csv to Online_Retail.csv
Dataset loaded successfully!

In [3]:
print("First 5 rows:")
display(df.head())

print("Dataset shape:")
print(df.shape)

print("Column names:")
print(df.columns.tolist())

print("Dataset information:")
df.info()

First 5 rows:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/01/2010 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/01/2010 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/01/2010 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/01/2010 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/01/2010 08:26:00,3.39,17850.0,United Kingdom

Dataset shape:
(541909, 8)
Column names:
['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']
Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [4]:
print("Missing values in each column:")
print(df.isnull().sum())

print("\nMissing values percentage:")
print((df.isnull().sum() / len(df)) * 100)

Missing values in each column:
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

Missing values percentage:
InvoiceNo       0.000000
StockCode       0.000000
Description     0.268311
Quantity        0.000000
InvoiceDate     0.000000
UnitPrice       0.000000
CustomerID     24.926694
Country         0.000000
dtype: float64

In [5]:
df_clean = df.copy()

important_columns = ["InvoiceNo", "Quantity", "UnitPrice"]

df_clean = df_clean.dropna(subset=important_columns)

print("Shape before cleaning:", df.shape)
print("Shape after handling missing important values:", df_clean.shape)

print("\nRemaining missing values:")
print(df_clean.isnull().sum())

Shape before cleaning: (541909, 8)
Shape after handling missing important values: (541909, 8)

Remaining missing values:
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [6]:
print("Repeated InvoiceNo values:")
print(df_clean["InvoiceNo"].duplicated().sum())

print("\nExample of repeated invoices:")
display(df_clean[df_clean["InvoiceNo"].duplicated(keep=False)].head(10))

Repeated InvoiceNo values:
516009

Example of repeated invoices:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/01/2010 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/01/2010 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/01/2010 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/01/2010 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/01/2010 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/01/2010 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/01/2010 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,12/01/2010 08:28:00,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,12/01/2010 08:28:00,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12/01/2010 08:34:00,1.69,13047.0,United Kingdom

In [7]:
print("Exact duplicate rows before removal:")
print(df_clean.duplicated().sum())

df_clean = df_clean.drop_duplicates()

print("Exact duplicate rows after removal:")
print(df_clean.duplicated().sum())

Exact duplicate rows before removal:
5268
Exact duplicate rows after removal:
0

In [8]:
df_clean["UnitPrice"] = pd.to_numeric(
    df_clean["UnitPrice"], errors="coerce"
)

valid_prices = df_clean[df_clean["UnitPrice"] >= 0]

highest_price_product = valid_prices.loc[
    valid_prices["UnitPrice"].idxmax()
]

print("Highest-priced product:")
print("Product:", highest_price_product["Description"])
print("Unit Price:", highest_price_product["UnitPrice"])

Highest-priced product:
Product: Manual
Unit Price: 38970.0

In [9]:
df_clean["Quantity"] = pd.to_numeric(
    df_clean["Quantity"], errors="coerce"
)

df_clean["Revenue"] = (
    df_clean["Quantity"] * df_clean["UnitPrice"]
)

display(df_clean[["InvoiceNo", "Description", "Quantity", "UnitPrice", "Revenue"]].head())

  InvoiceNo                          Description  Quantity  UnitPrice  Revenue
0    536365   WHITE HANGING HEART T-LIGHT HOLDER         6       2.55    15.30
1    536365                  WHITE METAL LANTERN         6       3.39    20.34
2    536365       CREAM CUPID HEARTS COAT HANGER         8       2.75    22.00
3    536365  KNITTED UNION FLAG HOT WATER BOTTLE         6       3.39    20.34
4    536365       RED WOOLLY HOTTIE WHITE HEART.         6       3.39    20.34

In [10]:
country_revenue = df_clean.groupby("Country")["Revenue"].sum()

print("Revenue by country:")
print(country_revenue.sort_values(ascending=False))

Revenue by country:
Country
United Kingdom          8167128.184
Netherlands              284661.540
EIRE                     262993.380
Germany                  221509.470
France                   197317.110
Australia                137009.770
Switzerland               56363.050
Spain                     54756.030
Belgium                   40910.960
Sweden                    36585.410
Japan                     35340.620
Norway                    35163.460
Portugal                  29302.970
Finland                   22326.740
Channel Islands           20076.390
Denmark                   18768.140
Italy                     16890.510
Cyprus                    12858.760
Austria                   10154.320
Hong Kong                  9908.240
Singapore                  9120.390
Israel                     7901.970
Poland                     7213.140
Unspecified                4740.940
Greece                     4710.520
Iceland                    4310.000
Canada                     3666.380
Malta                      2505.470
United Arab Emirates       1902.280
USA                        1730.920
Lebanon                    1693.880
Lithuania                  1661.060
European Community         1291.750
Brazil                     1143.600
RSA                        1002.310
Czech Republic              707.720
Bahrain                     548.400
Saudi Arabia                131.170
Name: Revenue, dtype: float64

In [11]:
highest_revenue_country = country_revenue.idxmax()
highest_revenue = country_revenue.max()

print("Highest revenue country:", highest_revenue_country)
print("Total revenue:", highest_revenue)

Highest revenue country: United Kingdom
Total revenue: 8167128.184

In [12]:
product_revenue = (
    df_clean.groupby("Description")["Revenue"]
    .sum()
    .sort_values(ascending=False)
)

print("Top 10 products by revenue:")
display(product_revenue.head(10))

Top 10 products by revenue:

Description
DOTCOM POSTAGE                        206245.48
REGENCY CAKESTAND 3 TIER              164459.49
WHITE HANGING HEART T-LIGHT HOLDER     99612.42
PARTY BUNTING                          98243.88
JUMBO BAG RED RETROSPOT                92175.79
RABBIT NIGHT LIGHT                     66661.63
POSTAGE                                66230.64
PAPER CHAIN KIT 50'S CHRISTMAS         63715.24
ASSORTED COLOUR BIRD ORNAMENT          58792.42
CHILLI LIGHTS                          53746.66
Name: Revenue, dtype: float64

In [13]:
print("Rows with negative unit prices:")
display(df_clean[df_clean["UnitPrice"] < 0].head())

print("Rows with zero unit prices:")
display(df_clean[df_clean["UnitPrice"] == 0].head())

print("Rows with zero or negative quantities:")
display(df_clean[df_clean["Quantity"] <= 0].head())

Rows with negative unit prices:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
299983,A563186,B,Adjust bad debt,1,08/12/2011 14:51:00,-11062.06,NaN,United Kingdom,-11062.06
299984,A563187,B,Adjust bad debt,1,08/12/2011 14:52:00,-11062.06,NaN,United Kingdom,-11062.06

Rows with zero unit prices:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
622,536414,22139,NaN,56,12/01/2010 11:52:00,0.0,NaN,United Kingdom,0.0
1970,536545,21134,NaN,1,12/01/2010 14:32:00,0.0,NaN,United Kingdom,0.0
1971,536546,22145,NaN,1,12/01/2010 14:33:00,0.0,NaN,United Kingdom,0.0
1972,536547,37509,NaN,1,12/01/2010 14:33:00,0.0,NaN,United Kingdom,0.0
1987,536549,85226A,NaN,1,12/01/2010 14:34:00,0.0,NaN,United Kingdom,0.0

Rows with zero or negative quantities:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
141,C536379,D,Discount,-1,12/01/2010 09:41:00,27.50,14527.0,United Kingdom,-27.50
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,12/01/2010 09:49:00,4.65,15311.0,United Kingdom,-4.65
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,12/01/2010 10:24:00,1.65,17548.0,United Kingdom,-19.80
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,12/01/2010 10:24:00,0.29,17548.0,United Kingdom,-6.96
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,12/01/2010 10:24:00,0.29,17548.0,United Kingdom,-6.96

In [14]:
print("Unique country names before standardization:")
print(df_clean["Country"].unique())

Unique country names before standardization:
['United Kingdom' 'France' 'Australia' 'Netherlands' 'Germany' 'Norway'
 'EIRE' 'Switzerland' 'Spain' 'Poland' 'Portugal' 'Italy' 'Belgium'
 'Lithuania' 'Japan' 'Iceland' 'Channel Islands' 'Denmark' 'Cyprus'
 'Sweden' 'Austria' 'Israel' 'Finland' 'Bahrain' 'Greece' 'Hong Kong'
 'Singapore' 'Lebanon' 'United Arab Emirates' 'Saudi Arabia'
 'Czech Republic' 'Canada' 'Unspecified' 'Brazil' 'USA'
 'European Community' 'Malta' 'RSA']

In [15]:
df_clean["Country"] = df_clean["Country"].astype("string").str.strip().str.title()

print("Country names after standardization:")
print(df_clean["Country"].unique())

Country names after standardization:
<StringArray>
[      'United Kingdom',               'France',            'Australia',
          'Netherlands',              'Germany',               'Norway',
                 'Eire',          'Switzerland',                'Spain',
               'Poland',             'Portugal',                'Italy',
              'Belgium',            'Lithuania',                'Japan',
              'Iceland',      'Channel Islands',              'Denmark',
               'Cyprus',               'Sweden',              'Austria',
               'Israel',              'Finland',              'Bahrain',
               'Greece',            'Hong Kong',            'Singapore',
              'Lebanon', 'United Arab Emirates',         'Saudi Arabia',
       'Czech Republic',               'Canada',          'Unspecified',
               'Brazil',                  'Usa',   'European Community',
                'Malta',                  'Rsa']
Length: 38, dtype: string

In [16]:
print("Final dataset shape:")
print(df_clean.shape)

print("\nMissing values:")
print(df_clean.isnull().sum())

print("\nDuplicate rows:")
print(df_clean.duplicated().sum())

print("\nFinal dataset preview:")
display(df_clean.head())

Final dataset shape:
(536641, 9)

Missing values:
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135037
Country             0
Revenue             0
dtype: int64

Duplicate rows:
0

Final dataset preview:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/01/2010 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,12/01/2010 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/01/2010 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/01/2010 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/01/2010 08:26:00,3.39,17850.0,United Kingdom,20.34

In [17]:
df_clean.to_csv("Online_Retail_Business_Analysis_Cleaned.csv", index=False)

from google.colab import files
files.download("Online_Retail_Business_Analysis_Cleaned.csv")